from selenium import webdriver
from time import sleep
# driver=webdriver.Firefox()
# driver.get('http://www.51zxw.net')
# driver.find_element_by_link_text('程序开发').click()
# sleep(2)
# # driver.back()
# driver.find_element_by_partial_link_text('考点讲解').click()
# sleep(2)
# driver.quit()
driver=webdriver.Firefox()
driver.get('http://www.baidu.com')
# driver.find_element_by_xpath('//input[@id=\'kw\']').send_keys('selenium')
# driver.find_element_by_xpath('//input[@name=\'wd\']').send_keys('python')
driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/div[1]/div/form/span[1]/input').send_keys('科比')
driver.find_element_by_id('su')
sleep(2)
driver.get('http://www.51zxw.net')
driver.back()
sleep(3)
driver.quit()